#starts off with dev so that we can differntiate in app engine.  As app engine cuts words off.
application: dev-srl-sketchsruface
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: testFiles.app

- url: /testList
  script: testFiles.app

- url: /src/test/web
  static_dir: src/test/web
  application_readable: true

- url: /src
  static_dir: src/main/web

- url: /test
  static_dir: src/test/web
  application_readable: true

- url: /images
  static_dir: src/main/resources/images

- url: /bower_components
  static_dir: bower_components

- url: /*
  script: testFiles.app
